NIHR_HIC_ICU_0108:
  shortName: hrate
  dataItem: Heart rate
  distribution: normal
  decimal_places: 0
  range:
    labels:
      amber: "[0, 20), (220,250]"
    apply: drop_entry
  missingness:
    impute_2d:
      lead: 3
      lag: 3
      fun: median
# NIHR_HIC_ICU_0093:
#   shortName: sex
#   dataItem: Sex
#   distribution: binary
#   category:
#     levels: # beware case-sensitive
#       M: male
#       F: female
# NIHR_HIC_ICU_0097:
#   shortName: dead_icu
#   dataItem: Dead or alive on discharge
#   distribution: binary
#   category:
#     levels:
#       A: Alive
#       D: Dead
#       E: Alive - not discharged
#     apply: drop_entry
